# Generated by Django 2.2.6 on 2022-10-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221014_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={
                'default_related_name': 'posts',
                'ordering': ('-pub_date',),
            },
        ),
    ]
