# Generated by Django 2.2.16 on 2022-11-01 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20221031_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_related_name': 'comments',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name='Дата создания'
            ),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='following',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=None,
                        related_name='follower',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
