# Generated by Django 2.2.16 on 2022-11-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221107_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_related_name': 'comments',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={
                'default_related_name': 'posts',
                'ordering': ('-pub_date',),
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
